version: '3'

services:

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
#    ports:
#      - 3389:3389
    restart: unless-stopped

networks:
  default:
    external:
      name: edge
