version: '3'

services:

  scheduler:
    image: py2
    container_name: scheduler
    volumes:
      - ./:/python-docker/
    environment:
      - FLASK_DEBUG=1
    ports:
     - 5000:5000
 

    restart: unless-stopped

